### ISSUE TITLE
Add a Privacy policy

### ISSUE THREAD

**Issue by PEPERSO** [ushnisha/tranquility-reader-webextensions#15]
Hi ! 

Could you please add your privacy policy to the firefox extension page ? (I hope you don't collect any data, but I prefer asking)

Thanks for your work :)

**Comment by ushnisha** [comment]
Hi Peperso,

Thanks for the question.  The answer is -- the extension runs on your browser; it does not send data to any website (it can only fetch data of a web page based on a user action and then transform and render that webpage in a readable format).

Data is saved on your browser (preferences, offline articles, etc.) but again none of this information is sent to any website.

There is no plan to add any such functionality (sending/storing data to a remote website).

But I will anyway add a more formal privacy policy to the extension page and to the github pages.

**Comment by PEPERSO** [comment]
Thanks for your precision and your respectful privacy policy !

**Comment by ushnisha** [comment]
Fixed with release 3.0.16 as part of commit 850a374

Refer to the file PRIVACY.md for more details.
