### ISSUE TITLE
Scroll buttons issue

### ISSUE THREAD

**Issue by DenB10** [ushnisha/tranquility-reader-webextensions#25]
Hi,
I updated to version 3.0.19 and I noticed the new scroll buttons don't work on offline pages.
Best regards

**Comment by ushnisha** [comment]
Hi DenB10,

Thanks for catching this bug.  I've fixed the problem now, but it will take a couple of weeks for me to submit another version; I'm trying to figure out a couple of other issues and will submit all of them together as a single release later in the month.

The fix should work even for pages that you save for offline reading (in version 3.0.19) between now and when the next release will become available later in the the month.

**Comment by ushnisha** [comment]
Fixed in 3.0.20; please re-open if you see any problems.
