### ISSUE TITLE
Don't truncate end of page option

### ISSUE THREAD

**Issue by ye110wd** [ushnisha/tranquility-reader-webextensions#31]
I read many pages where there is a "next page" or numbered "1 2 3 ..." link at the bottom of the page.

Tranquility reader often removes those links because of how the page is coded, like it should.

I would like a "Don't truncate end of page" option added to preference.

The result would be very messy but it's the end of page anyway.

Much appreciated. I've used this addon on at least 7,000 pages.

**Comment by ushnisha** [comment]
The extension tries to "save" navigation links such as "next page" as well as numbered links -- and at the end of the cleanup of the page, it tries to restore these navigation links at the top/bottom of the transformed page; the problem *may* be in how the extension identifies these links and cases where it fails to work on some pages (depending on how those pages are created/structured).

If you can provide some examples where the extension fails to identify these links, I can try to add these patterns to retain -- or if there is a bug in the code, these pages may help identify the bug that is missing them.  Thanks!

**Comment by ye110wd** [comment]
https://www.sousetsuka.com/2018/05/okami-wa-nemuranai-12.html
https://lightnovelstranslations.com/i-woke-up-piloting-the-strongest-starship-so-i-became-a-space-mercenary/prologue/
https://lightnovelbastion.com/novel/death-mage/volume-1/chapter-0/

Here are some. There are hundreds more

I honestly don't think there is neat solution. I'm asking for a messy solution as a last resort catch all.
An untruncated option in preferences would be perfect. I'd actually like to have everything in the "main column" (even comments) untrucated. From head to tail complete.

In my opinion there are way too many non-standard page layouts for a neat solution. Tranquility reader already works very well for most standard pages.

**Comment by ye110wd** [comment]
another two. 
https://www.kitchennovel.com/2020/09/15/tondemo-skill-001-caught-up-in-a-hero-summoning-spell/
https://wad14151.wordpress.com/2020/12/16/riot-grasper-vol-1-chapter-1/

**Comment by ushnisha** [comment]
Sorry for the delay in getting back on this issue.

Thanks for the links; as you have rightly pointed out, there are too many patterns (or none at all in some cases) to handle this cleanly.

The extension code at this time does not handle a page based on "columns" of content -- I'll have to figure out the best way to do this; often determining a "main column" will require that the page is completely loaded (all CSS and javascript related rendering completed) -- currently, the extension often gets the underlying page without any of this loading completed and processes the data without any knowledge of the layout of the page/elements by the browser.

I'll have to see if I can let users customize or teach the extension how to process specific pages that it does not do a good job on.  I'm not entirely sure how amenable the code is to decouple the current processing and such user specified processing.

No matter what the solution, this will require quite of bit of work and testing.  I'll leave this issue open as a placeholder for that.

In the meanwhile, I've tried to add a few more search patterns to determine previous/next article links; they don't work for most of the examples you have provided (maybe for a couple of them).

**Comment by ye110wd** [comment]
I've tested on many sites since the update. Probably 40+.
Tranquility Reader now works on many more sites. There are very few sites where it does not work now. I think it's good enough not to need further fix.

Thank you very much for the update.
