### ISSUE TITLE
partnership

### ISSUE THREAD

**Issue by RaeAtBiscience** [ushnisha/tranquility-reader-webextensions#46]
Hello, we're looking to buy some analytics from your browser extension for our internal product. Please contact me back at: Rae@biscience.com

**Comment by Fmstrat** [comment]
Please don't do this.

**Comment by ushnisha** [comment]
Thank you for your interest.

Please refer to the privacy policy of the extension: https://github.com/ushnisha/tranquility-reader-webextensions/blob/master/PRIVACY.md

The extension runs on the browser of the user; it does not collect or transmit any information to any external website.  There is no plan to change this policy.  

As a result, there is nothing to share or sell either.
