### ISSUE TITLE
Mail to ushnisha support address fails?

### ISSUE THREAD

**Issue by LorenAmelang** [ushnisha/tranquility-reader-webextensions#7]
Tried to eMail twice since 31 Aug, both returned:

This is the mail system at host gateway13.unifiedlayer.com.
<DELETED - for privacy reasons>: delivery temporarily suspended: lost
   connection with mta5.am0.yahoodns.net[67.195.228.109] while sending RCPT TO

Yes, I'm sending to the "arunk" at "ushnisha" dot "com" address that used to work. Are you still there?

**Comment by ushnisha** [comment]
Email forwarding failure caused the emails to bounce.  The problem has now been addressed.  I will open a separate ticket for the problem identified in your bounced email.  Thanks!
